### ISSUE TITLE
Complete 'win' functionality

### ISSUE THREAD

**Issue by harrymilnes** [Pdut89/Minesweeper#4]
Implement functionality to declare a victory to the user when the only outstanding tiles are mines.

Expected result: When the only undiscovered tiles left are mines the game should declare a victory
Actual Result: When the only undiscovered tiles left are mines the game is still on going

**Comment by harrymilnes** [comment]
@Pdut89 Could you tag this 'Hacktoberfest' so that other participants can pick this up

**Comment by ScottHarrisonDev** [comment]
I'll take this one 👍
